In [ ]:
import pandas as pd
from itertools import combinations

In [2]:
# Global Variables
FILE_PATH: str = "https://raw.githubusercontent.com/vinayak-ensemble/Dataset-TV-Shows-OTT/refs/heads/main/tv-shows.csv" 
OTT_DF: pd.DataFrame = pd.read_csv(FILE_PATH)

In [75]:
OTT_DF.head()

,id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,platform
0,1,Movie,ChuChuTV Surprise Eggs Learning Videos (English),NaN,NaN,NaN,"October 18, 2019",2019,TV-Y,61 min,Children & Family Movies,From colors and letters to animals of all kind...,Netflix
1,2,Movie,The Journey Is the Destination,Bronwen Hughes,"Ben Schnetzer, Kelly Macdonald, Sam Hazeldine,...",United States,"November 7, 2017",2016,R,123 min,Dramas,Spirited 22-year-old activist and photojournal...,Netflix
2,3,TV Show,Champions,NaN,"Anders Holm, Fortune Feimster, Andy Favreau, J...",United States,"June 19, 2021",2018,TV-14,1 Season,TV Comedies,"Years after getting his girlfriend pregnant, w...",Netflix
3,4,TV Show,The Returned,NaN,"Anne Cosigny, Frédéric Pierrot, Clotilde Hesme...",France,"February 17, 2019",2015,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Horror",On returning home and finding they're believed...,Netflix
4,5,Movie,Super Bheem Bana Vajraveer,Sumit Das,"Sonal Kaushal, Rupa Bhimani, Julie Tejwani, Sa...",India,"June 18, 2019",2018,TV-Y7,63 min,Children & Family Movies,"Hoping to find a magical root, a monster has c...",Netflix

In [ ]:
# Check for columns and null values present in the dataframe

OTT_DF.info()

<class 'pandas.DataFrame'>
RangeIndex: 9338 entries, 0 to 9337
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            9338 non-null   int64
 1   type          9338 non-null   str
 2   title         9338 non-null   str
 3   director      6483 non-null   str
 4   cast          8400 non-null   str
 5   country       8376 non-null   str
 6   date_added    9325 non-null   str
 7   release_year  9338 non-null   int64
 8   rating        9331 non-null   str
 9   duration      9335 non-null   str
 10  listed_in     9338 non-null   str
 11  description   9338 non-null   str
 12  platform      9338 non-null   str
dtypes: int64(2), str(11)
memory usage: 948.5 KB

In [ ]:
# Count the null values in each column and the respective % for the same

pd.DataFrame(OTT_DF.isnull().sum(), columns=['count']).join(
    pd.DataFrame((OTT_DF.isnull().sum() / OTT_DF.shape[0] * 100).apply(lambda x: str(round(x, 2)) + " %"), columns=['percentage']),
    how='left'
)

              count percentage
id                0      0.0 %
type              0      0.0 %
title             0      0.0 %
director       2855    30.57 %
cast            938    10.04 %
country         962     10.3 %
date_added       13     0.14 %
release_year      0      0.0 %
rating            7     0.07 %
duration          3     0.03 %
listed_in         0      0.0 %
description       0      0.0 %
platform          0      0.0 %

In [ ]:
# Analysing the combined value columns are other important columns

def check_unique(df: pd.DataFrame, col: str, label: str = None):
    if label is None:
        label = col
    print(f"Unique {label} Combinations: ", df[col].dropna().nunique())
    print(f"Unique {label} :", len(list(filter(lambda x: x != '', set(', '.join(df[col].dropna().unique()).split(', '))))))

check_for_cols = ['director', 'cast', 'country', 'listed_in', 'platform']
for col in check_for_cols:
    check_unique(OTT_DF, col)
    print('_'*50, end='\n\n')

# Conclusion:
# - director: There are some movies that have more than 1 director.
# - cast: The unique count is roughly 4x compared to it's combination.
# - country: The data covers most of the countries (121 / 195).
# - listed_in: The combination values is roughly 10x compared to it's unique count.
# - platform: Platform doesn't have any combinations, there is only a single value for each
#   - The rating and description might vary in the 2 platforms [there may be duplicates]

Unique director Combinations:  4630
Unique director : 5059
__________________________________________________

Unique cast Combinations:  8079
Unique cast : 35957
__________________________________________________

Unique country Combinations:  733
Unique country : 121
__________________________________________________

Unique listed_in Combinations:  825
Unique listed_in : 84
__________________________________________________

Unique platform Combinations:  2
Unique platform : 2
__________________________________________________